# Generated by Django 4.0 on 2022-01-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0004_alter_subscription_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('author', 'subscriber')},
        ),
    ]
